// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimeZoneClient is the client API for TimeZone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeZoneClient interface {
	WhatTimeIsIt(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeReply, error)
}

type timeZoneClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeZoneClient(cc grpc.ClientConnInterface) TimeZoneClient {
	return &timeZoneClient{cc}
}

func (c *timeZoneClient) WhatTimeIsIt(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeReply, error) {
	out := new(TimeReply)
	err := c.cc.Invoke(ctx, "/timezone.TimeZone/WhatTimeIsIt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeZoneServer is the server API for TimeZone service.
// All implementations must embed UnimplementedTimeZoneServer
// for forward compatibility
type TimeZoneServer interface {
	WhatTimeIsIt(context.Context, *TimeRequest) (*TimeReply, error)
	mustEmbedUnimplementedTimeZoneServer()
}

// UnimplementedTimeZoneServer must be embedded to have forward compatible implementations.
type UnimplementedTimeZoneServer struct {
}

func (UnimplementedTimeZoneServer) WhatTimeIsIt(context.Context, *TimeRequest) (*TimeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhatTimeIsIt not implemented")
}
func (UnimplementedTimeZoneServer) mustEmbedUnimplementedTimeZoneServer() {}

// UnsafeTimeZoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeZoneServer will
// result in compilation errors.
type UnsafeTimeZoneServer interface {
	mustEmbedUnimplementedTimeZoneServer()
}

func RegisterTimeZoneServer(s grpc.ServiceRegistrar, srv TimeZoneServer) {
	s.RegisterService(&TimeZone_ServiceDesc, srv)
}

func _TimeZone_WhatTimeIsIt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeZoneServer).WhatTimeIsIt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timezone.TimeZone/WhatTimeIsIt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeZoneServer).WhatTimeIsIt(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeZone_ServiceDesc is the grpc.ServiceDesc for TimeZone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeZone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timezone.TimeZone",
	HandlerType: (*TimeZoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhatTimeIsIt",
			Handler:    _TimeZone_WhatTimeIsIt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/helloworld.proto",
}
